scheduleConfig:
  - name: Mindy Duong
    calendarId: mn2esq1loakpq2844tp47mo2s98i4hrs@import.calendar.google.com
    phoneNumber: "+18582055744"
  - name: Manny Quaidoo
    calendarId: 44ehk3kvrvcmt9j6dtmth7vuek4tbh67@import.calendar.google.com
    phoneNumber: "+15852550897"
  - name: Nick Stark
    calendarId: vo51lggmrdhbejbnrf2a7cd3rhvu0bbj@import.calendar.google.com
    phoneNumber: "+16058309672"
defaultPhoneNumber: "+18582055744"
defaultName: Mindy Duong
